Final
hannanabid124/Djangoo pull request #4
Opened 2023-09-05 20:39 UTC by hannanabid124

2023-09-08 12:26 UTC, UsamaSadiq requested changes
Also update the UI templates to make it more intuitive. Run the project and add usage screenshots on the PR as results.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/consumers.py
> +        print('chat connected')
Try adding logs instead of printing to the console. Logs are always preferred when deploying a project to production.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/forms.py
> +        fields = ['username', 'password1', 'password2']
follow the PEP8 convention to always add a blank line at the end of every python file.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/tests.py
> +class CoreConsumerTests(TestCase):
No tests written for CoreConsumerTests class. You can remove this class altogether if you're not planning to add any tests in it.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/urls.py
> +    path('individual_chats/', views.individual_chats, name='individual_chats'),
Redundant path added. You can remove this line. 
```suggestion
```

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/room/models.py
> +class IndiviualChat(models.Model):
Refactor the model name correctly and update all usages and instances. You'll also need to create new migrations after this change.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/views.py
> +            login(request, user)
Instead of logging in the user, redirect the user to the login page so he can use the credentials to sign in.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/room/models.py
> +    reciver = models.ForeignKey(User, related_name='reciver', on_delete=models.CASCADE)
field name also needs to be updated to `receiver` instead.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/core/views.py
> +    messages = IndiviualChat.objects.filter(sender=request.user, reciver=user) | IndiviualChat.objects.filter(sender=user, reciver=request.user)
Couldn't we do something like this instead? 
```
filter(sender = request.user or user, receiver = user or request.user) 
```
or any other similar approach to avoid querying the db two times.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/djangochat/asgi.py
> +import os
explain why do we need to define `asgi.py` file?

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/djangochat/settings.py
> +from telnetlib import LOGOUT
why use this specific package `telnetlib`?

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/room/admin.py
> +admin.site.register(Room)
We could also register models to admin using the registerr decorator function. have a look at the docs and implement register decorator on the models to add them to admin instead.

2023-09-08 12:26 UTC, UsamaSadiq commented on djangochat 2(Done)/room/consumers.py
> +        recivername = event['recivername']
Typo. needs to be corrected.

2023-09-09 14:58 UTC, hannanabid124 commented on djangochat 2(Done)/core/views.py
> +    messages = IndiviualChat.objects.filter(sender=request.user, reciver=user) | IndiviualChat.objects.filter(sender=user, reciver=request.user)
I have make object Q that is built in Django for complex queries. Updated code is

messages = IndividualChat.objects.filter(
    Q(sender=request.user, receiver=user) | Q(sender=user, receiver=request.user)
)

2023-09-09 15:01 UTC, hannanabid124 commented on djangochat 2(Done)/djangochat/asgi.py
> +import os
We are dealing with web sockets and asgi.py file is mostly defined when you have to take things asynchronous. Django traditionally runs on the WSGI. In summary, the asgi.py file is necessary when you want to run Django in an asynchronous environment, such as when building real-time or WebSocket-based applications.

2023-09-09 15:05 UTC, hannanabid124 commented on djangochat 2(Done)/djangochat/settings.py
> +from telnetlib import LOGOUT
Sir when i was testing the project. it was giving some error, so was searching how can we remove the error. I have removed this line of code from setting.py file.

2023-09-12 09:46 UTC, UsamaSadiq requested changes
Please add screenshots of the project output and use cases as well.

2023-09-12 09:46 UTC, UsamaSadiq commented on djangochat 2(Done)/core/consumers.py
> +        Message.objects.create(user=user, room=room, content=message)
Add an empty new line at the end.

2023-09-12 09:46 UTC, UsamaSadiq commented on djangochat 2(Done)/room/admin.py
> +admin.site.register(Room)'''
Remove the commented code and add a new line at the end.

2023-09-12 09:46 UTC, UsamaSadiq commented on djangochat 2(Done)/room/consumers.py
> +        IndividualChat.objects.create(sender=sender, receiver=receiver, message=message )
Need new empty line at the end.

2023-09-12 09:46 UTC, UsamaSadiq commented on djangochat 2(Done)/room/models.py
> +        ordering = ('date_added',)
New empty line needed at the end.

2023-09-12 17:37 UTC, merged